server:
  port: 20200
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/erp?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
mybatis-plus:
  mapper-locations: classpath:./mapper/*.xml

file:
  path: D:\oneFile

