spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oneyi?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none #  update 自动更新   none  不变化
    show-sql: true  #日志中显示sql语句
  application:
    name: spring-data-jpa-demo
server:
  port: 2333 #端口号
