package GradingLevel

import top.oneyi.pojo.GradingLevel

dialect  "mvel"

rule "grading_rule01"
    when
       $gradingLevel: GradingLevel(scoreInterval >= 0 && scoreInterval < 100)
    then
    System.out.println("该份值为 10");
end

rule "grading_rule02"
    when
        $gradingLevel: GradingLevel(scoreInterval >= 100 && scoreInterval < 200)
    then
    System.out.println("该份值为 20");
end

rule "grading_rule03"
    when
       $gradingLevel:  GradingLevel(scoreInterval >= 200 && scoreInterval < 300)
    then
    System.out.println("该份值为 30");
end

rule "grading_rule04"
    when
        $gradingLevel: GradingLevel(scoreInterval >= 300 && scoreInterval < 500)
    then
    System.out.println("该份值为 40");
end

rule "grading_rule05"
    when
        $gradingLevel: GradingLevel(scoreInterval >= 500 && scoreInterval < 600)
    then
    System.out.println("该份值为 50");
end
