server:
  port: 10101
## MQTT##
mqtt:
  host: tcp://116.62.155.98:1883
  userName: admin
  passWord: admin
  qos: 1
  clientId: ClientId_local_2 #ClientId_local必须唯一 比如你已经定了叫ABC  那你就一直叫ABC  其他地方就不要使用ABC了
  timeout: 10
  keepalive: 20
  topic1: oneer

