# 插入用户
POST http://localhost:2333/customer
Content-Type: application/json

{
  "name": "admin",
  "password": "admin",
  "age": "12",
  "email": "jkkj@gmain.com",
  "createTime": "",
  "createBy": "",
  "updateTime": "",
  "updateBy": ""
}

###
# 删除 用户
DELETE http://localhost:2333/customer/3
Content-Type: application/json

###
# 修改用户
PUT http://localhost:2333/customer/
Content-Type: application/json

{
  "id": 3,
  "name": "admin",
  "password": "admin",
  "objectVersion": 0,
  "age": "1211",
  "email": "jkkj@gmain.com",
  "createTime": "2023-03-24 15:45:43",
  "createBy": "我是用户名",
  "updateTime": "2023-03-24 15:45:43",
  "updateBy": ""
}

###
# 查询全部用户
GET http://localhost:2333/customer
Content-Type: application/json

###
# 根据id查询用户
GET http://localhost:2333/customer/3
Content-Type: application/json

###
# 根据name查询用户
GET http://localhost:2333/customer/name?name=admin


###

GET http://localhost/40155/api/system/loanApplicationInfo/loanApplicationIist?Authorization=Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpblR5cGUiOiJsb2dpbiIsImxvZ2luSWQiOiJzeXNfdXNlcjoxIiwicm5TdHIiOiJ2MHQzUDZkdThjdzBNWUhpU24xZ2g5Wm5HQ2pDeWtVayJ9.cRTLe_0-6eiJ9OmWoFdJiy2pDMnfvHVo3ntYpnOOx88



