server:
  port: 8014

spring:
  application:
    name: workflow
  datasource:
    name: mysqlDatasource
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/activiti?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

    # 监控统计拦截的filters，如果启用log4j记得添加依赖
  #    filters: stat,wall
  # activiti
  activiti:
    #每次应用启动不检查Activiti数据表是否存在及版本号是否匹配，提升应用启动速度
    database-schema-update: true
    #在项目单独作为一个引擎，本身不部署流程的时候，如果resources目录没有“processes”目录，启动项目报错–找不到processes目录。需要在配置文件中添加以下内容：
    check-process-definitions: false
    process-definition-location-prefix: classpath:/processes/
    process-definition-location-suffixes:
      -**.bpmn
      -**.bpmn20.xml
    #保存历史数据级别设置为full最高级别，便于历史数据的追溯
    history-level: full
  # activiti 安全访问
#  security:
#    basic:
#      enabled: true
#    user:
#      name: root
#      password: root
mybatis:
  mapper-locations: classpath:mapper/*.xml  # xml文件路径
  type-aliases-package: top.oneyi.pojo.po
  configuration:
    map-underscore-to-camel-case: true   # 开启驼峰
logging:
  level:
    com.zoctan.api.mapper: debug

