server:
  port: 1011
spring:
  application:
    ## 指定服务名称
    name: one-server
#  cloud:
#    nacos:
#      discovery:
#        # nacos的服务地址，nacos-server中IP地址:端口号
#        server-addr: 127.0.0.1:8848