server:
  port: 20200
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/new_wms?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
  rabbitmq:
    host: 116.62.155.98
    port: 5672
    virtual-host: /
    username: admin
    password: admin
  mybatis:
    mapper-locations: classpath:mapper/*.xml  # xml文件路径
    type-aliases-package: top.oneyi.pojo.po
    configuration:
      map-underscore-to-camel-case: true   # 开启驼峰
knife4j:
  # 开启增强配置
  enable: true
  setting:
    enableSwaggerModels: true
    swaggerModelName: 实体类
  #开启生产环境屏蔽
  production: false
