server:
  port: 1010
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oneyi?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
  devtools:
    restart:
      enabled: true  # 开启热部署
      additional-paths: mybatis-plus-demo/src/main/java #重启目录
      additional-exclude: WEB-INF/**
  freemarker:
    cache: false # 页面不加缓存,修改时生效
# 配置mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



