spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flowable?useSSL=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
flowable:
  async-executor-activate: false
