server:
  port: 1010
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oneyi?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
  rabbitmq:
    host: 116.62.155.98
    port: 5672
    virtual-host: /
    username: admin
    password: admin
    publisher-confirms: true
mybatis:
  mapper-locations: classpath:mapper/*.xml  # xml文件路径
  type-aliases-package: top.oneyi.pojo.po
  configuration:
    map-underscore-to-camel-case: true   # 开启驼峰

