server:
  port: 8091
  tomcat:
    max-threads: 10 # 修改tomcat的最大并发值修改为10,默认是200
spring:
  application:
    name: service-order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://116.62.155.98:3306/shop?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    username: test
    password: 123456
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: a8cde16e-6cf9-4143-af18-b8e7481482a3
    sentinel:
      transport:
        port: 9999 #跟控制台交流的端口,随意指定一个未使用的端口即可
        dashboard: localhost:8080 # 指定控制台服务的地址
